{
    "score": "87.5",
    "comments": "====================\nTests for Part 1:\nSuccesses: 10\nFailures: 0\n\n====================\nTests for Part 2:\ntest_case05 (workspace.testing_suite_full.Part2TestCase) Traceback (most recent call last):\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 473, in test_case05\n    self.run_with_params(5, self.params, self.test_method, self.student_method)\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 386, in run_with_params\n    test_params['max_steps']))\nAssertionError: Part 2 - Test Case 5: robot took 1000 step(s) which exceeded the 1000 allowable step(s).\n\nSuccesses: 9\nFailures: 1\n\n====================\nTests for Part 3:\nSuccesses: 10\nFailures: 0\n\n====================\nTests for Part 4:\ntest_case01 (workspace.testing_suite_full.Part4TestCase) Traceback (most recent call last):\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 565, in test_case01\n    self.run_with_params(1, self.params, self.test_method, self.student_method)\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 386, in run_with_params\n    test_params['max_steps']))\nAssertionError: Part 4 - Test Case 1: robot took 1000 step(s) which exceeded the 1000 allowable step(s).\n\ntest_case04 (workspace.testing_suite_full.Part4TestCase) Traceback (most recent call last):\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 574, in test_case04\n    self.run_with_params(4, self.params, self.test_method, self.student_method)\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 386, in run_with_params\n    test_params['max_steps']))\nAssertionError: Part 4 - Test Case 4: robot took 1000 step(s) which exceeded the 1000 allowable step(s).\n\ntest_case07 (workspace.testing_suite_full.Part4TestCase) Traceback (most recent call last):\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 583, in test_case07\n    self.run_with_params(7, self.params, self.test_method, self.student_method)\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 386, in run_with_params\n    test_params['max_steps']))\nAssertionError: Part 4 - Test Case 7: robot took 1000 step(s) which exceeded the 1000 allowable step(s).\n\ntest_case09 (workspace.testing_suite_full.Part4TestCase) Traceback (most recent call last):\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 589, in test_case09\n    self.run_with_params(9, self.params, self.test_method, self.student_method)\n  File \"/home/grader/polygonrobot/workspace/testing_suite_full.py\", line 386, in run_with_params\n    test_params['max_steps']))\nAssertionError: Part 4 - Test Case 9: robot took 1000 step(s) which exceeded the 1000 allowable step(s).\n\nSuccesses: 6\nFailures: 4\n\n====================\nOverall Score: 87.5\n"
}